# Generated by Django 4.2.30 on 2026-07-16 16:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Município')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('codigo_ibge', models.CharField(db_index=True, max_length=7, unique=True, verbose_name='Código IBGE')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geometria')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo (processamento científico)')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque na Home')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['uf', 'nome'],
            },
        ),
    ]
