# Generated by Django 4.2.30 on 2026-07-16 16:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Estação')),
                ('station_type', models.CharField(choices=[('davis', 'Davis'), ('ecowitt', 'Ecowitt'), ('ambient', 'Ambient Weather'), ('iot', 'IoT'), ('manual', 'Manual'), ('csv', 'CSV Importado')], default='manual', max_length=50, verbose_name='Tipo de Estação/Origem')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localização Espacial')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='farms.farm', verbose_name='Fazenda')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
        ),
    ]
