# Generated by Django 4.2.30 on 2026-07-16 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data do Cálculo')),
                ('scale', models.IntegerField(choices=[(3, 'SPI-3'), (6, 'SPI-6'), (12, 'SPI-12')], verbose_name='Escala Temporal (meses)')),
                ('value', models.FloatField(verbose_name='Valor do SPI')),
                ('classification', models.CharField(choices=[('extremamente_umido', 'Extremamente Úmido'), ('muito_umido', 'Muito Úmido'), ('normal', 'Normal'), ('seca_moderada', 'Seca Moderada'), ('seca_severa', 'Seca Severa'), ('seca_extrema', 'Seca Extrema')], max_length=50, verbose_name='Classificação')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spi_results', to='farms.farm', verbose_name='Fazenda')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spi_results', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spi_results', to='stations.station', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Resultado do SPI',
                'verbose_name_plural': 'Resultados do SPI',
                'unique_together': {('date', 'scale', 'station')},
            },
        ),
    ]
