# Generated by Django 4.2.30 on 2026-08-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiresult',
            name='classification',
            field=models.CharField(choices=[('extremamente_umido', 'Extremamente Úmido'), ('muito_umido', 'Muito Úmido'), ('moderadamente_umido', 'Moderadamente Úmido'), ('normal', 'Normal'), ('seca_moderada', 'Seca Moderada'), ('seca_severa', 'Seca Severa'), ('seca_extrema', 'Seca Extrema')], max_length=50, verbose_name='Classificação'),
        ),
    ]
