# Generated by Django 4.2.30 on 2026-07-16 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('drought', 'Alerta de Seca'), ('excess_rain', 'Alerta de Excesso de Chuva'), ('water_risk', 'Risco Hídrico'), ('anomaly', 'Anomalia Climática')], max_length=50, verbose_name='Tipo de Alerta')),
                ('message', models.TextField(verbose_name='Mensagem do Alerta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='farms.farm', verbose_name='Fazenda')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stations.station', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Alerta Climático',
                'verbose_name_plural': 'Alertas Climáticos',
                'ordering': ['-created_at'],
            },
        ),
    ]
