# Generated by Django 4.2.30 on 2026-08-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('drought', 'Alerta de Seca'), ('excess_rain', 'Alerta de Excesso de Chuva'), ('water_risk', 'Risco Hídrico'), ('anomaly', 'Anomalia Climática'), ('inconsistency', 'Possível Inconsistência')], max_length=50, verbose_name='Tipo de Alerta'),
        ),
    ]
