# Generated by Django 4.2.30 on 2026-07-16 16:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Projeção')),
                ('scenario', models.CharField(max_length=100, verbose_name='Cenário Climático')),
                ('value', models.FloatField(verbose_name='Precipitação Projetada (mm)')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='farms.farm', verbose_name='Fazenda')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='stations.station', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Projeção Climática',
                'verbose_name_plural': 'Projeções Climáticas',
            },
        ),
        migrations.CreateModel(
            name='ChirpsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('value', models.FloatField(verbose_name='Precipitação Estimada (mm)')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localização da Célula')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chirps_records', to='farms.farm', verbose_name='Fazenda')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chirps_records', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chirps_records', to='stations.station', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Dado CHIRPS',
                'verbose_name_plural': 'Dados CHIRPS',
            },
        ),
        migrations.CreateModel(
            name='RainfallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Medição')),
                ('value', models.FloatField(verbose_name='Precipitação (mm)')),
                ('source_type', models.CharField(choices=[('chirps', 'CHIRPS'), ('manual', 'Manual'), ('station', 'Estação'), ('imported_csv', 'CSV Importado'), ('api', 'API Externa')], default='manual', max_length=50, verbose_name='Origem do Dado')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_records', to='farms.farm', verbose_name='Fazenda')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_records', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_records', to='stations.station', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Dado de Precipitação',
                'verbose_name_plural': 'Dados de Precipitação',
                'unique_together': {('date', 'station', 'source_type')},
            },
        ),
    ]
