# Generated by Django 4.2.30 on 2026-07-16 17:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirpsdata',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chirps_records', to='maps.municipio', verbose_name='Município (média zonal)'),
        ),
        migrations.AlterField(
            model_name='chirpsdata',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localização de Referência'),
        ),
        migrations.AlterUniqueTogether(
            name='chirpsdata',
            unique_together={('municipio', 'date')},
        ),
    ]
