# Generated by Django 4.2.30 on 2026-08-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0002_chirpsdata_municipio_alter_chirpsdata_geom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainfalldata',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='rainfalldata',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário da Medição'),
        ),
    ]
