# Generated by Django 4.2.30 on 2026-08-23 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('farms', '0003_farm_poligono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('climate', '0003_rainfalldata_notes_rainfalldata_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChirpsValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_pares', models.IntegerField(verbose_name='Nº de dias comparados')),
                ('r2', models.FloatField(verbose_name='R²')),
                ('rmse', models.FloatField(verbose_name='RMSE (mm)')),
                ('mae', models.FloatField(verbose_name='MAE (mm)')),
                ('mbe', models.FloatField(verbose_name='MBE (mm) — viés médio')),
                ('indice_d', models.FloatField(verbose_name='Índice d (Willmott)')),
                ('indice_c', models.FloatField(verbose_name='Índice c (Camargo-Sentelhas)')),
                ('desempenho_c', models.CharField(choices=[('otimo', 'Ótimo'), ('muito_bom', 'Muito Bom'), ('bom', 'Bom'), ('mediano', 'Mediano'), ('sofrivel', 'Sofrível'), ('mau', 'Mau'), ('pessimo', 'Péssimo')], max_length=20, verbose_name='Desempenho (índice c)')),
                ('calculado_em', models.DateTimeField(auto_now=True, verbose_name='Calculado em')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chirps_validations', to='farms.farm', verbose_name='Fazenda')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chirps_validations', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chirps_validation', to='stations.station', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Validação CHIRPS × Local',
                'verbose_name_plural': 'Validações CHIRPS × Local',
            },
        ),
    ]
