# Generated by Django 4.2.30 on 2026-08-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('climate', '0004_chirpsvalidation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projection',
            unique_together={('date', 'scenario', 'station')},
        ),
    ]
