# Generated by Django 4.2.30 on 2026-07-16 16:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Fazenda')),
                ('city', models.CharField(max_length=100, verbose_name='Município')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Área (hectares)')),
                ('crop', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cultura Agrícola')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localização Espacial')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
        ),
    ]
