# Generated by Django 4.2.30 on 2026-08-23 11:55

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ['name'], 'verbose_name': 'Fazenda', 'verbose_name_plural': 'Fazendas'},
        ),
        migrations.AddField(
            model_name='farm',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='maps.municipio', verbose_name='Município'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Município (texto livre, legado)'),
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Talhão')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Área (hectares)')),
                ('crop', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cultura Agrícola')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localização Espacial')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='farms.farm', verbose_name='Fazenda')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Talhão',
                'verbose_name_plural': 'Talhões',
                'ordering': ['name'],
            },
        ),
    ]
