# Generated by Django 4.2.30 on 2026-08-23 12:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_alter_farm_options_farm_municipio_alter_farm_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='poligono',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Contorno da Propriedade (opcional)'),
        ),
    ]
